title: 'redp4w // security notes'
description: 'Writeups, walkthroughs e estudos em segurança ofensiva e defensiva por Jezer Ferreira.'
url: 'https://redp4w.github.io'
baseurl: ''
lang: pt-BR
timezone: America/Sao_Paulo
markdown: kramdown
highlighter: rouge
permalink: /notes/:title/
theme: jekyll-theme-hacker
show_excerpts: true
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
